# Generated by Django 3.1.7 on 2021-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('заказ', '0002_auto_20210413_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('не доставлен', 'не доставлен'), ('доставлен', 'доставлен')], max_length=200, null=True),
        ),
    ]
